build_script:
    - gradlew.bat --no-daemon assemble

test_script:
    - gradlew.bat --no-daemon check

environment:
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0  # Use 64-bit Java

cache:
    - C:\Users\appveyor\.gradle

artifacts:
    - path: 'app/build/libs/scenebuilder-*.jar'
      name: JAR
